name: Publish to AUR

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PKGBUILD
        run: bash .github/generate-pkgbuild.sh

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: ww-manager
          pkgbuild: ./PKGBUILD
          commit_username: ${{ github.repository_owner }}
          commit_email: ${{ github.repository_owner }}@users.noreply.github.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update AUR package and .SRCINFO"
          ssh_keyscan_types: rsa,ecdsa,ed25519
